name: Auth Service CI

on:
  push:
    paths:
      - "services/auth/**"
  pull_request:
    paths:
      - "services/auth/**"

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/auth

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.7

      - name: Install deps
        run: go mod tidy

      - name: Build
        run: go build ./cmd

      - name: Run Tests
        run: go test ./... -v
